# Generated by Django 2.2.6 on 2019-10-26 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectNote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='body',
            new_name='description',
        ),
    ]
