# Generated by Django 2.2.6 on 2019-10-27 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectNote', '0002_auto_20191026_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=255)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ProjectNote.Note')),
            ],
        ),
    ]
