# Generated by Django 2.2.6 on 2019-10-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectNote', '0003_noteitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, help_text='Max Characters: 255', max_length=255, null=True, verbose_name='Note Description:'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(help_text='Max Characters: 100', max_length=100, verbose_name='Note Title:'),
        ),
        migrations.AlterField(
            model_name='noteitem',
            name='body',
            field=models.CharField(help_text='Max Characters: 255', max_length=255),
        ),
    ]
