# Generated by Django 2.2.6 on 2019-10-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectNote', '0005_auto_20191027_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
