# Generated by Django 2.2.6 on 2019-10-28 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectNote', '0006_noteitem_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noteitem',
            options={'ordering': ['order']},
        ),
    ]
