# Generated by Django 2.2.6 on 2019-10-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectNote', '0008_auto_20191028_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteitem',
            name='body',
            field=models.CharField(max_length=255),
        ),
    ]
